name: code_coverage
description: A CLI tool and package useful for reporting code coverage of a given dart package
version: 2.1.0
repository: https://github.com/gustavo-hillesheim/dart-code-coverage

environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  code_coverage:

dependencies:
  path: ^1.7.0
  args: ^2.0.0
  coverage: ^1.0.2
  ansicolor: ^2.0.1
  yaml: ^3.1.0
  cli_table: ^1.0.2
  dart_console: ^4.1.1

dev_dependencies:
  test: ^1.16.8
  lints: ^5.1.1
